#!/usr/bin/env pythons
# -*- coding: utf-8 -*-

words = [['LARANJA', 'GOIABA', 'TANGERINA', 'JABUTICABA', 'JAMELÃO', 'MORANGO','MARACUJÁ','ABACATE', 'MELANCIA', 'MELÃO', 'CARAMBOLA', 'ABACAXI', 'CEREJA', 'PÊRA', 'FRAMBOESA', 'AMORA', 'LIMÃO', 'FIGO', 'PÊSSEGO', 'BANANA', 'MAMÃO', 'MANGA', 'LICHIA', 'DAMASCO', 'FRUTA DO CONDE',
 'AMEIXA', 'ROMÃ', 'UVA', 'CAQUI', 'COCO', 'CUPUAÇU', 'CACAU', 'CAJU', 'GRAVIOLA', 'GUARANÁ', 'PITANGA', 'ACEROLA', 'KIWI'], 

['POLVO', 'LAGOSTA', 'CAMARÃO', 'MACACO', 'GORILA', 'GATO', 'PORCO', 'COELHO', 'PORCO-ESPINHO', 'CAVALO-MARINHO', 'ARARA', 'PATO', 'URUBU', 'POMBO', 'SARDINHA','BALEIA', 'GOLFINHO', 'TARTARUGA',
 'ELEFANTE', 'GIRAFA', 'ARANHA', 'CACHORRO', 'CALOPSITA', 'PAPAGAIO', 'HIPOPÓTAMO', 'PEIXE-BOI', 'SUCURI', 'JARARACA', 'MICO-LEÃO-DOURADO', 'BARATA', 'LAGARTO', 'LAGARTIXA', 'MOSCA', 'MOSQUITO', 'RATO',
 'JACARE', 'CAMELO', 'CAMALEÃO', 'FORMIGA', 'GANSO', 'MARRECO', 'GAIVOTA', 'TIGRE', 'LEÃO', 'ARRAIA', 'BAIACU', 'CUPIM', 'ALCE', 'VEADO', 'ZEBRA', 'GIRAFA', 'COALA', 'SURICATO', 'FOCA', 'ORNITORRINCO'
, 'URSO', 'VACA', 'BOI', 'OVELHA', 'CABRA', 'PAVÃO', 'BEIJA-FLOR', 'CANGURU', 'MAMUTE', 'BORBOLETA','GUEPARDO', 'RINOCERONTE', 'TUCANO', 'BABUÍNO', 'TAMANDUÁ', 'ESQUILO', 'CUTIA'] ,

['AFEGANISTÃO', 'ÁFRICA DO SUL', 'ALBÂNIA', 'ALEMANHA', 'ANDORRA', 'ANGOLA', 'ARÁBIA SAUDITA', 'ARGÉLIA', 'ARGENTINA', 'ARMÊNIA', 'AUSTRÁLIA', 'ÁUSTRIA', 'AZERBAIJÃO', 'BAHAMAS', 'BANGLADESH', 'BARBADOS', 'BÉLGICA', 'BELIZE', 'BIELORÚSSIA', 'BOLÍVIA', 'BÓSNIA HERZEGOVINA', 
 'BOTSUANA', 'BRASIL', 'BULGÁRIA', 'BUTÃO', 'CABO VERDE', 'CAMARÕES', 'CAMBOJA', 'CANADÁ', 'CATAR', 'CAZAQUISTÃO', 'CHILE', 'CHINA', 'CHIPRE', 'CINGAPURA', 'COLÔMBIA', 'CONGO', 'CORÉIA DO NORTE', 'CORÉIA DO SUL', 'COSTA DO MARFIM', 'COSTA RICA', 'CROÁCIA',
 'CUBA', 'DINAMARCA', 'EGITO', 'EL SALVADOR', 'EMIRADOS ÁRABES UNIDOS', 'EQUADOR', 'ESCÓCIA', 'ESLOVÁQUIA', 'ESLOVÊNIA', 'ESPANHA', 'ESTADOS UNIDOS', 'ESTÔNIA', 'ETIÓPIA', 'RUSSIA', 'FIJI', 'FILIPINAS', 'FINLÂNDIA', 'FRANÇA', 'GABÃO', 'GÃMBIA', 'GANA', 'GEÓRGIA',
 'GRÃ-BRETANHA', 'GRANADA', 'GRÉCIA', 'GROENLÂNDIA', 'GUATEMALA',  'GUIANA', 'GUIANA FRANCESA', 'GUINÉ', 'GUINÉ BISSAU', 'GUINÉ EQUATORIAL', 'HAITI', 'HOLANDA', 'HONDURAS', 'IÊMEN', 'INDIA', 'INDONÉSIA', 'IRÃ', 'IRAQUE', 'IRLANDA', 'IRLANDA DO NORTE', 'ISLÂNDIA',
 'ISRAEL', 'ITÁLIA', 'JAMAICA', 'JAPÃO', 'JORDÂNIA', 'KUWAIT', 'LAOS', 'LETÔNIA', 'LÍBANO', 'LIBÉRIA', 'LÍBIA', 'LITUÃNIA', 'LUXEMBURGO', 'MACEDÔNIA', 'MADAGASCAR', 'MALÁSIA', 'MALDIVAS', 'MALTA', 'MARROCOS', 'MAURITÂNIA', 'MÉXICO', 'MICRONÉSIA', 'MOÇAMBIQUE',
 'MONGÓLIA', 'NAMÍBIA', 'NEPAL', 'NICARÁGUA', 'NIGÉRIA', 'NORUEGA', 'NOVA ZELÂNDIA', 'PANAMÁ', 'PAPUA NOVA GUINÉ', 'PAQUISTÃO', 'PARAGUAI', 'PERU', 'POLÔNIA', 'PORTO RICO', 'PORTUGAL', 'QUÊNIA', 'QUIRQUISTÃO', 'REINO UNIDO', 'REPÚBLICA DOMINICANA', 'REPÚBLICA TCHECA',
 'ROMÊNIA', 'RUANDA', 'SAMOA', 'SENEGAL', 'SERRA LEOA', 'SÉRVIA E MONTENEGRO', 'SÍRIA', 'SOMÁLIA', 'SRI LANKA', 'SUDÃO', 'SUÉCIA', 'SUÍÇA', 'SURINAME', 'TADJIQUISTÃO', 'TAILÂNDIA', 'TANZÃNIA', 'TOGO', 'TRINIDAD E TOBAGO', 'TUNÍSIA', 'TURCOMENISTÃO', 'TURQUIA', 'TUVALU',
 'UCRÂNIA', 'UGANDA', 'URUGUAI', 'UZBEQUISTÃO', 'VENEZUELA', 'VIETNÃ', 'ZAIRE', 'ZÂMBIA', 'ZIMBÁBUE']                                                 

] 